<a href="https://colab.research.google.com/github/ollihansen90/Mathe-SH/blob/main/Mathe%5ESH_Prog_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathe^SH Python-Kurs, Woche 8

# Fragen?
Solltet ihr Fragen zum Code oder Probleme mit Colab haben, schickt uns gerne eine Mail:

*   hohansen@inb.uni-luebeck.de
*   maren.wieder@student.uni-luebeck.de
*   friederike.meissner@student.uni-luebeck.de
*   dustin.haschke@student.uni-luebeck.de

# Packages

Angenommen, wir wollen eine Funktion ```pythagoras``` definieren, die für die Katheten $a$ und $b$ die Länge der Hypotenuse $c$ mit dem Satz des Pythagoras berechnet. Dieser besagt bekanntlich $a^2 + b^2 = c^2$, d.h. $c = \sqrt{a^2+b^2}$. Beim Implementieren in Python fällt auf, dass eine Funktion wie ```sqrt(x)``` per se nicht definiert ist und wir stattdessen $x^{\frac{1}{2}}$ verwenden müssen. Das sieht aufgrund der vielen Exponenten etwas unübersichtlich aus, funktioniert aber natürlich.

In [ ]:
def pythagoras(a,b):
    # c = sqrt(a**2 + b**2)         # funktioniert nicht, da sqrt() nicht definiert
    c = (a**2 + b**2) ** (1/2)
    return c

pythagoras(3,4)

5.0

Für viele weitere mathematische Anwendungen, die z.B. $sin(x)$ oder eine bestimmte Anzahl zufällig erzeugter Werte benötigen, finden wir allerdings nicht immer eine Alternative, außer selbst eine Funktion zu implementieren.

Genau dafür gibt es sogenannte **Packages**, bestehend aus **Modulen**. Das sind strukturierte Zusammenfassungen bereits definierter Funktionen zu einem oder mehreren Anwendungsbereichen, die die Kernfunktionen von Python beliebig erweitern, während die Übersicht über das eigene Programm beibehalten wird. Der Aufbau entspricht einem Hauptverzeichnis, dem Package, das sich in mehrere Unterordner bzw. Module aufteilt, die wiederum unterteilt sein können.

Dabei gibt es einerseits Bibliotheken (Libraries), die die Standardbibliothek und Module von Drittanbietern umfassen, andererseits können auch selbst Module definiert werden. Das ermöglicht es uns, ohne copy & paste immer wieder "alte" Funktionen zu verwenden und Fehler einfach an einem Ort zu korrigieren!


## Bereits verwendete Packages

Auch wenn ihr euch vielleicht nicht direkt daran erinnern könnt, an ein paar Stellen von diesem Kurs habt ihr bereits verschiedene packages verwendet, oder zumindet Teile von welchen.

### Woche 4: "Bonus: Numpy-Arrays"
Das package ```numpy``` wird generell benötigt, um das Rechnen mit Listen zu ermöglichen. Die Routine ```np.arange(0,10)``` liefert hierbei eine spezielle Liste mit den Zahlen 0, 1, 2, ..., 9 und wir können diese Liste schlichtweg mit "*2" kombinieren, wohingegen dies mit einer Liste, die über ```range``` erstellt wurde, nicht funktionieren wird. Stattdessen wir die Liste verdoppelt.

In [ ]:
import numpy as np
data = np.arange(0,10)*2
liste = list(range(10))*2
print(data)
print(liste)

# Permutation
data_perm = data[[0,1,2,3,9,2,2,3]]
print(data_perm)

# Punktweise Wahrheitsabfrage
data_bool = data_perm>5
print(data_bool)
# Beispiel: Setze alle Werte größer 5 auf 10 und alle Werte kleinergleich 5 auf 0
data_neu = data_perm
data_neu[data_neu<=5] = 0
data_neu[data_neu>5] = 10
print(data_neu)

[ 0  2  4  6  8 10 12 14 16 18]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6 18  4  4  6]
[False False False  True  True False False  True]
[ 0  0  0 10 10  0  0 10]


### Woche 5: "Der ```re.findall()```-Befehl"

Die Abkürzung ```re``` steht für den Ausdruck "regular expression" und der Befehl ```findall``` tut exakt das, was sein Name beschreibt: er findet alle (nicht überlappenden) Treffer für ein bestimmtes Muster in einem String. In dem Beispiel aus der Übung, wurde das Muster "asen" in dem String "string" gesucht.

In [ ]:
import re

string = "Hasen in 100 Extasen lasen aus 99 Seifenblasen auf dem Rasen 2021"
gefundene = re.findall("asen", string)
print(gefundene)

#Der Eingangsbefehl ist für die Verwendung von re.findall() erforderlich:
import re
text = "Der reine Keim des Sein ist wie ein feiner Reim, ohne Leim, mit Wein."

#Gib hier deinen Code ein



satz =  "Viele Fische fliegen fortan vielen fernen Vögel fort."

neu = re.findall('\\bf\w+\\b', satz)       #findet alle Wörter im 'satz', die mit f beginnen
neu_zwei = re.findall('\\bv\w+\\b', satz)  #findet alle Wörter im 'satz', die mit v beginnen

print (neu)
print(neu_zwei)

['asen', 'asen', 'asen', 'asen', 'asen']
['fliegen', 'fortan', 'fernen', 'fort']
['vielen']


### Woche 5: "Projekt: Texte auf Internetseiten"

In dem Projekt von Olli wurden zwei packages verwendet und zwar ```requests``` und ```bs4```. Da ihr diese allerdings niemals selber direkt verwendet habt, wollten wir euch hier nur einmal kurz an diese erinnern.

In [ ]:
import requests                 # Package, das Internetseiten laden kann
from bs4 import BeautifulSoup   # Package, das heruntergeladene Internetzseiten "hübsch" macht

# -------------------- LINK ---------------------
link = "https://de.wikipedia.org/wiki/Mathematik" # Den Link hier könnt ihr gerne ändern
# -----------------------------------------------

r = requests.get(link) # lade Seiteninhalt runter
soup = BeautifulSoup(r.text) # mache Inhalt "hübsch"
text = "".join([data.get_text() for data in soup.find_all("p")]) # ziehe NUR Texte aus r

# entferne Sonderzeichen
sonderzeichen = ['Ζ', 'Χ', 'Ε', 'Β', 'ό', 'Ω', 'Θ', '΄', 'φ', '•', 'π', 'Γ', 'ζ', 'Ρ', 'ά', 'Μ', 'Η', 'σ', 'Λ', 'ώ', 'δ', 'Φ', 'ψ', 'Ο', 'Έ', 'Α', 'Ά', 'Ι', 'Ξ', 'Δ', 'Ϝ', 'Ϟ', 'ξ', 'ί', '^', 'γ', 'Ν', 'ε', 'Τ', 'Σ', 'Υ', 'Ψ', 'ϊ', 'Κ', '\\', 'ə', '»', '«', 'ω', 'ύ', 'Π', 'æ', '≥', '³', 'µ', '>', 'ā', '½', 'î', '=', 'β', 'υ', 'ī', 'č', 'ο', 'ἰ', 'ς', '!', 'ἴ', 'ū', 'ρ', 'λ', 'ð', 'ú', '€', "'", 'Á', 'ō', 'ó', '̑', '±', '"', 'í', '%', '°', 'á', 'ɔ', '+', '|', 'ø', 'ɪ', '͡', '−', '→', '§', 'ʃ', '*', '&', '̯', ':', 'χ', '1', '–', 'α', ')', ';', '…', '[', 'É', 'ν', '0', '\xad', 'ː', '5', '‘', '4', '„', 'é', '9', '8', '.', 'ˈ', '7', 'τ', '(', 'μ', '“', 'ç', '\xa0', '/', '-', '”', 'η', 'θ', 'è', '3', 'ß', '{', '?', '‚', 'ή', '6', '2', 'ι', '’', ',', 'κ', ']', 'έ', 'ē', '}']
for zeichen in sonderzeichen:
    text = text.replace(zeichen, "")

#print(text)

### Woche 7: "Generatoren"

Aus dem package ```sys``` wurde an dieser Stelle kurz ```getsizeof```verwendet, allerdings auch nicht ausführlich, sondern nur, um einen der großen Vorteile von Generatoren zu verdeutlichen: der bedeutend geringere Bedarf an Speicher.

In [ ]:
from sys import getsizeof

def funktion(n):
    liste = []
    for i in range(n):
        liste.append(i**2)
    return liste

def generator(n):
    for i in range(n):
        yield i**2

liste_fun = funktion(1_000_000)
print(getsizeof(liste_fun))
liste_gen = generator(1_000_000)
print(getsizeof(liste_gen))

8697472
128


## Einbauen von Packages

Wo ihr nun diese Beispiele alle wieder vor Augen geführt bekommen habt, dürfte euch wohl eine große Gemeinsamkeit aufgefallen sein: das Verwenden von ```import```.

Die einfachste Option ist natürlich, dass gesamte package zu importieren beziehungsweise zu "laden". Dies sieht in der Regel so aus: ```import nameDesPackage```

In [ ]:
import math
import random

print(math.sqrt(9 + 16))

5.0

Doch manchmal sind uns die Namen von diesen packages zu lang oder wir empfinden es als unübersichtlich. In diesem Rahmen benutzen wir dann ```as```.

In [1]:
import math as m

print(m.sqrt(9 + 16))

5.0


Wenn wir nicht direkt immer das komplette package importieren wollen, können wir auch noch ```from``` benutzen. Dies hat auch den zusätzlichen Vorteil, dass wir die geladenen Funktionen direkt aufrufen können.

In [ ]:
from math import sqrt

print(sqrt(9 + 16))

5.0

# Ein paar Packages
In diesem Abschnitt möchten wir euch ein paar Packages vorstellen, die wir in Zukunft häufiger verwenden möchten.
## ```math```
Das Package ```math``` haben wir eben schon kennengelernt. Es erweitert Python um Funktionen der Mathematik, mit denen wir alle möglichen Berechnungen erstellen können.
## ```random```
Das Package ```random``` liefert uns Funktionen zum Generieren von Zufallszahlen. Wichtig ist hierbei zu wissen, dass der Computer niemals "echte" Zufallszahlen generieren kann, wir reden also von "Pseudozufall".

Es gibt eine Vielzahl weiterer Packages die Pseudozufallszahlen generieren können. In der nächsten Woche werden wir beispielsweise näher auf ```numpy``` eingehen. Oftmals benötigt man allerdings nicht die ganzen Strukturen, die aufwendigere Packages liefern, daher kann man stattdessen einfach ```random``` benutzen.

In dem Codebeispiel wird eine gleichverteilte Zufallszahl gezogen. "Gleichverteilung" bedeutet, dass die Wahrscheinlichkeit für jedes Ereignis immer gleich ist. Ihr kennt Gleichverteilungen bereits bei Würfeln! Das Ereignis "würfle eine 3" hat die gleiche Wahrscheinlichkeit wir "würfle eine 1".



In [14]:
import random

zufallszahl = random.random()
print(zufallszahl)

zufall_0_10 = 10*zufallszahl
print(zufall_0_10)

def gleichvertZufall(von=0, bis=1):
    z = random.random()
    output = (bis-von)*z+von
    return output

for i in range(10):
    print(gleichvertZufall(-3, 10))

0.34832460249408126
3.4832460249408124
5.340668361975252
-2.4497317756070025
-0.35008480537385234
4.370600680981202
9.627538834861001
7.440913795844816
-1.5630550030386625
-2.3081653499418167
8.515043128457165
5.58335159161366


## ```datetime```
Das Package ```datetime``` ist ein built-in-Package von Python, mit dem man mit Daten und Uhrzeiten rechnen kann. 

In [34]:
from datetime import datetime as dt

print(dt.now().month)
print(dt.now().year)
print(dt.now().microsecond)

12
2021
859133


#Übung 1 - Importieren

Schreibe einen Code, welcher das Package ```math``` importiert und die Befehle ```math.sin(x)``` bzw. ```.cos(x)``` und ```.tan(x)```  mit ```x=100``` einerseits als auch mit ```x = 2.6*pi``` andererseits ausgibt.

Hinweis: Pi ist auch eine Funktion des *Package* math, welches über ```math.pi``` aufgerufen werden kann.

Überprüfe anschließend deine Lösung mit den Zahlen unter dem Code.

In [ ]:
# dein Code zur ersten Importierübung:



Die ersten Ziffern der **richtigen Lösung** lauten:

**-0.506**
**0.862**
**0.587**

bzw.

**0.951**
**-0.309**
**-3.07**

#Übung 2 - Eigeninitiative

Die Arbeit eines Programmierers besteht häufig aus Nachschlagen von Methoden, Funktionen, Lösungen. Das sollst du jetzt auch tun.

Suche in der offiziellen Python-Dokumentation zum *package* ```datetime``` unter nachfolgendem Link nach einer Möglichkeit den Wochentag auszugeben (Englisch: *weekday*)

https://docs.python.org/3.6/library/datetime.html?highlight=datetime#datetime.datetime

Wende danach den Befehl auf ```geburtstag_zuse``` und ```geburtstag_meiner``` an, nachdem du bei Letzterem deinen eigenen Geburtstag eingetragen hast. Beachte dafür das dafür erforderliche Format der Datumseingabe.

Lösungshinweis: Zuse, der Entwickler des ersten Computers, ist an einem Mittwoch geboren worden; die entsprechende Funktion beschreibt das mit der Ausgabe einer ```2```

In [ ]:
import datetime

geburtstag_meiner = datetime.date(2001,6,7)
geburtstag_zuse = datetime.date(1910,6,22)

#Hier folgt dein Code:

2

##Übung 2 - Zusatz

Wenn du magst, dann kannst du deine obige Funktion so erweitern, dass anstelle von Zahlen die konkreten Wochentage, also anstatt 0 Montag, anstatt 1 Dienstag usw., ausgegeben werden.

Nutze hierfür z.B. ```if```, ```elif``` und ```else```

#Übung 3 - 1001 mal würfeln

Importiere zunächst das ```random``` *Package*.

Nutze eine Funktion des ```random``` *Packages*, um einen normalen 6-seitigen Würfel mit Augenzahlen zwischen 1 und 6 insgesamt 1001 mal zu würfeln. (Verwende dafür z.B. eine ```for```-Schleife)

Addiere alle Ergebnisse und gebe die Summe auf der Konsole aus.

Gebe anschließend den Mittelwert aller Würfe auf der Konsole aus.

#Übung 4 Chaos

Schreibe eine Funktion, die eine zweihundertfünfzigtausend mal Zahlen zwischen 1 und 99 würfelt.
Addiere dazu den Wert des heutigen Wochentages (rechechiere ggf. in dem Dokumentationslink von Aufgabe 2).

Bilde hiervon den Mittelwert, teile ihn anschließend mit Abrunden durch 5 mittels ```//``` und multipliziere dann mit Pi.
Berechne hiervon den Kosinus und gebe ihn auf der Konsole aus.

Importiere alle *Packages*, die dafür notwendig sind.

#Übung 5 - Vervollständigung & Ausblick auf nächste Stunde

Das folgende Programm ist fast fertig - nur noch der Anfangsteil fehlt.

Versuche den Code zum Laufen zu bringen, indem du diesen ergänzt.

.

Hinweis 1:
Der Code fügt benutzt unter anderem Funktionen aus der ersten Übung, implementiert sie aber etwas anders.

Berücksichtige das hinsichtlich der *Packages* entsprechend.

.

Hinweis 2:

Es wird das *Package* *matplotlib.pyplot* verwendet, welches wir nächste Stunde noch ausführlicher behandeln werden.
Dieses taucht nicht in der Standard-Dokumentation von Python auf und muss etwas anders importiert werden.

Siehe dir dafür auch das Beispiel unter folgendem Link an:

https://matplotlib.org/stable/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py

In [ ]:
#Hier folgt dein Code


#Hier endet dein Code
#Der folgende Code soll so bleiben:
points = 12
list_x = []
list_y = []

for i in range(0,points+1):
  list_x.append(m.cos((i*m.pi)/(points/2)))
  list_y.append(m.sin((i*m.pi)/(points/2)))

plt.plot(list_x,list_y);
#Hier endet der Code

NameError: ignored

#Übung 5 - Zusatz

Schreibe selbst nach dem Vorbild von 5 eine Funktion, die 30 Punkte einer Parabel zwischen x=-3 und x=3 abbildet.

Du kannst dafür gerne Teile von Aufgabe 5 komplett kopieren.

In [ ]:
#dein Parabel-Code folgt hier:
